oidc_provider/urls.py
try:
    from django.urls import url
except ImportError:
    from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from oidc_provider import (
    settings,
    views,
)

app_name = 'oidc_provider'
urlpatterns = [
    url(r'^authorize/?$', views.AuthorizeView.as_view(), name='authorize'),
    url(r'^token/?$', csrf_exempt(views.TokenView.as_view()), name='token'),
    url(r'^userinfo/?$', csrf_exempt(views.userinfo), name='userinfo'),
    url(r'^end-session/?$', views.EndSessionView.as_view(), name='end-session'),
    url(r'^\.well-known/openid-configuration/?$', views.ProviderInfoView.as_view(),
        name='provider-info'),
    url(r'^introspect/?$', views.TokenIntrospectionView.as_view(), name='token-introspection'),
    url(r'^jwks/?$', views.JwksView.as_view(), name='jwks'),
]

if settings.get('OIDC_SESSION_MANAGEMENT_ENABLE'):
    urlpatterns += [
        url(r'^check-session-iframe/?$', views.CheckSessionIframeView.as_view(),
            name='check-session-iframe'),
    ]

oidc_provider/templates/oidc_provider/authorize.html
<h1>Request for Permission</h1>

<p>Client <strong>{{ client.name }}</strong> would like to access this information of you ...</p>

<form method="post" action="{% url 'oidc_provider:authorize' %}">

    {% csrf_token %}

    {{ hidden_inputs }}

    <ul>
        {% for scope in scopes %}
        <li><strong>{{ scope.name }}</strong> <br><i>{{ scope.description }}</i></li>
        {% endfor %}
    </ul>

    <input type="submit" value="Decline" />
    <input name="allow" type="submit" value="Authorize" />

</form>

oidc_provider/templates/oidc_provider/check_session_iframe.html
{% load staticfiles %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>OP Iframe</title>
        <script src="{% static 'oidc_provider/js/sha256.min.js' %}"></script>
        <script language="JavaScript" type="text/javascript">
            window.addEventListener("message", receiveMessage, false);

            function receiveMessage(e) {
                if (!e.data || typeof e.data != 'string' || e.data == 'error') {
                    return;
                }

                var status;
                try {
                    var clientId = e.data.split(' ')[0];
                    var sessionState = e.data.split(' ')[1];
                    var salt = sessionState.split('.')[1];

                    var browserState = getOpBrowserState();

                    var sessionStateCalculated = sha256(clientId + ' ' + e.origin + ' ' + browserState + ' ' + salt) + '.' + salt;

                    if (sessionState == sessionStateCalculated) {
                        status = 'unchanged';
                    } else {
                        status = 'changed';
                    }
                } catch(err) {
                    status = 'error';
                }
                e.source.postMessage(status, e.origin);
            };

            function getOpBrowserState() {
                var theName = 'op_browser_state=';
                var theCookie = document.cookie + ';';
                var start = theCookie.indexOf(theName);
                if (start != -1)
                {
                    var end = theCookie.indexOf(';', start);
                    return unescape(theCookie.substring(start + theName.length, end));
                }
                throw new Error('We couldn\'t find the "op_browser_state" cookie.');
            }
        </script>
    </head>
    <body>
        OpenID Connect Session Management OP Iframe.
    </body>
</html>

oidc_provider/templates/oidc_provider/error.html
<h3>{{ error }}</h3>
<p>{{ description }}</p>

oidc_provider/templates/oidc_provider/hidden_inputs.html
<input name="client_id" type="hidden" value="{{ params.client_id }}" />
<input name="redirect_uri" type="hidden" value="{{ params.redirect_uri }}" />
<input name="response_type" type="hidden" value="{{ params.response_type }}" />
<input name="scope" type="hidden" value="{{ params.scope | join:' ' }}" />
<input name="state" type="hidden" value="{{ params.state }}" />
{% if params.nonce %}<input name="nonce" type="hidden" value="{{ params.nonce }}" />{% endif %}
{% if params.code_challenge %}<input name="code_challenge" type="hidden" value="{{ params.code_challenge }}" />{% endif %}
{% if params.code_challenge_method %}<input name="code_challenge_method" type="hidden" value="{{ params.code_challenge_method }}" />{% endif %}